version: "3.9"

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      -  "${PORT}:${PORT}"
    volumes:
      - ./:/home/app/docker-reload
    env_file:
      - .env.dev